Repository re3turn/twicrawler, pull requests merged in 2019-10, with the labels that each got.

#24 fix #12 open()をリトライ処理の中で実行するように変更
  app/google_photos.py
Labels: bug

#29 誤ってGoogle Photosに2重登録されないように変更
  app/twitter.py
Labels: bug

#28 Fix #17 #26 ConnectionError時にリトライするように変更
  app/google_photos.py
Labels: bug

#27 Fix #21 Google APIの成否に関わらずファイルを削除するように変更
  app/crawler.py
Labels: bug

#33 リファクタリング
  .idea/inspectionProfiles/Project_Default.xml
  README.md
  app/__init__.py
  app/crawler.py
  app/env.py
  app/google_photos.py
  app/store.py
  app/twitter.py
  get_refresh_token.py
  run.py
Labels: :recycle:

#41 🐛 requiredを指定していてもエラーにならない問題を修正
  app/env.py
Labels: :bug:

#40 ✨ add: media save to album. Fix #23
  README.md
  app/crawler.py
  app/google_photos.py
Labels: :sparkles:, enhancement

#44 🐛 公式RT先のメディアが取得できない問題を修正
  app/twitter.py
Labels: :bug: bug
